=== alexxtahi/projet_dsb_2/Q7-DTD.dtd
<!-- Racine -->
<!ELEMENT stock (glossaire?, categorie+)>

<!-- CatÃ©gorie -->
<!ELEMENT categorie (produit*)>
<!ATTLIST categorie id_cat CDATA #REQUIRED
                    lib_cat CDATA #REQUIRED>

<!-- Glossaire -->
<!ELEMENT glossaire (mot+)>
<!ATTLIST glossaire auteur CDATA #IMPLIED>
<!ELEMENT mot (#PCDATA)>
<!ATTLIST mot def CDATA #REQUIRED>

<!-- Produit -->
<!ELEMENT produit (nom_prod, descri_prod, prix_achat_prod, prix_vente_prod, qte_stock, date_peremption, date_appro)>
<!ATTLIST produit id_prod CDATA #REQUIRED>
<!ELEMENT nom_prod (#PCDATA | glossaire)*>
<!ELEMENT descri_prod (#PCDATA | glossaire)*>
<!ELEMENT prix_achat_prod (#PCDATA)>
<!ELEMENT prix_vente_prod (#PCDATA)>
<!ELEMENT qte_stock (#PCDATA)>
<!ELEMENT date_peremption (#PCDATA)>
<!ELEMENT date_appro (#PCDATA)>

=== alexxtahi/projet_dsb_2/Q8a-XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./Q10a-XML.css" type="text/css"?>
<!DOCTYPE stock SYSTEM "./Q7-DTD.dtd">

<!-- XML Schema -->
<stock>
    <!-- Glossaire -->
    <glossaire>
        <mot def="MCD">MCD (modèle conceptuel des données)</mot>
        <mot def="MOCODO">MOCODO (Modélisation Conceptuelle de Données. Nickel. Ni souris.)</mot>
    </glossaire>
    <categorie id_cat="cat_1" lib_cat="Viande">
        <!-- Produits -->
        <!-- prod 1 -->
        <produit id_prod="prod_1">
            <nom_prod>Filon de poulet</nom_prod>
            <descri_prod>
                Bouts de poulet sous forme de saucisse
                <glossaire auteur="Alex">
                    <mot def="Filon">Filon: Bout de poulet sous forme de saucisse</mot>
                    <mot def="Poulet">Poulet: Jeune volaille, mâle ou femelle, de la sous-espèce Gallus gallus domesticus, élevée pour sa chair</mot>
                </glossaire>
            </descri_prod>
            <prix_achat_prod>19.99</prix_achat_prod>
            <prix_vente_prod>39.99</prix_vente_prod>
            <qte_stock>47</qte_stock>
            <date_peremption>11/04/2025</date_peremption>
            <date_appro>11/04/2023</date_appro>
        </produit>
        <!-- prod 2 -->
        <produit id_prod="prod_2">
            <nom_prod>Jambon fumé</nom_prod>
            <descri_prod>
                Tranches de jambon fumé aux bois de boulogne
            </descri_prod>
            <prix_achat_prod>9.30</prix_achat_prod>
            <prix_vente_prod>19.00</prix_vente_prod>
            <qte_stock>26</qte_stock>
            <date_peremption>01/01/2023</date_peremption>
            <date_appro>31/12/2023</date_appro>
        </produit>
    </categorie>
</stock>
